# Generated by Django 5.0.6 on 2024-05-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_order_orderpakage_order_pakages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
