# Generated by Django 5.0.6 on 2024-05-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_order_pakages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.order')),
                ('pakage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.pakage')),
            ],
        ),
    ]
