# Generated by Django 5.0.6 on 2024-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_orderpakage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
