# Generated by Django 5.0.6 on 2024-05-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpakage',
            name='Exam_count',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='OrderPakageUseCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exam_crated', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.orderpakage')),
            ],
        ),
    ]
