# Generated by Django 5.0.6 on 2024-05-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_orderpakage_exam_count_orderpakageusecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.order'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pakage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.pakage'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
