# Generated by Django 5.0.6 on 2024-05-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_exam_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='submitted_at',
        ),
        migrations.CreateModel(
            name='Qestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.qestion'),
        ),
    ]
