# Generated by Django 5.0.6 on 2024-05-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_answer_correct_remove_answer_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.qestion'),
        ),
        migrations.AlterField(
            model_name='qestion',
            name='correct_answer',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='qestion',
            name='question',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
