# Generated by Django 5.0.6 on 2024-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_affiliate_affiliate_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='total_order',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='total_amunt',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
