# Generated by Django 5.0.6 on 2024-05-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_affiliate_total_order_alter_affiliate_affiliate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
    ]
