# Generated by Django 5.0.6 on 2024-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_affiliate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate_earning',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
