# Generated by Django 5.0.6 on 2024-06-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_user_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=800)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.qestion')),
            ],
        ),
        migrations.CreateModel(
            name='Package_Qestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True)),
                ('correct_answer', models.CharField(max_length=800)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.pakage')),
            ],
        ),
    ]
