# Generated by Django 5.0.6 on 2024-06-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_package_answer_package_qestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.package_qestion'),
        ),
    ]
