# Generated by Django 5.0.6 on 2024-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_alter_exam_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text="You will be provided with text from a document. Your task is to generate 5000 multiple-choice questions with correct answers based on the text. Remove the serial number from the questions. Start with 'question:'. The correct answer will start with 'answer:'. Options will start with 'options:'. All four options will be in a list format like options: ['option 1', 'option 2', 'option 3', 'option 4']. Ensure that 'answer:' appears after 'options:' for each question.")),
            ],
        ),
    ]
