# Generated by Django 5.0.6 on 2024-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pakage',
            name='docx',
            field=models.FileField(blank=True, help_text='Give here Genereated Question only no other data.like: {at.py}', null=True, upload_to='static/pdfs/pakage/'),
        ),
    ]
