# Generated by Django 5.0.6 on 2024-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_pakage_docx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakage',
            name='docx',
            field=models.FileField(blank=True, help_text='Give here Genereated Question only no other data.', null=True, upload_to='static/pdfs/pakage/'),
        ),
    ]
