# Generated by Django 4.0.8 on 2022-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.IntegerField(help_text='Enter 11 digits phone number', max_length=11, unique=True, verbose_name='Phone Number')),
            ],
        ),
    ]
